<img width=700px; src="../logo_cds.png">

# Introduction to numpy

This material is inspired from different source:

* https://github.com/SciTools/courses
* https://github.com/paris-saclay-cds/python-workshop/blob/master/Day_1_Scientific_Python/01-numpy-introduction.ipynb

### Difference between python list and numpy array

Python offers some data containers to store data. Lists are generally used since they allow for flexibility.

In [1]:
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

At a first glance, numpy array seems to offer the same capabilities.

In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To find the difference, we need to focus on the low-level implementation of these two containers.

A python list is a contiguous array in memory containing the references to the stored object. It allows for instance to store different data type object within the same list.

In [5]:
x = [1, 2.0, 'three']
x

[1, 2.0, 'three']

In [6]:
print('The type of x is: {}'.format(x))
for idx, elt in enumerate(x):
    print('The type of the {}-ith element is" {}'.format(idx, type(elt)))

The type of x is: [1, 2.0, 'three']
The type of the 0-ith element is" <class 'int'>
The type of the 1-ith element is" <class 'float'>
The type of the 2-ith element is" <class 'str'>


Numpy arrays, however, are directly storing the typed-data. Therefore, they are not meant to be used with mix type.

In [7]:
x = np.arange(3)
print('The type of x is: {}'.format(type(x)))
print('The data type of x is: {}'.format(x.dtype))

The type of x is: <class 'numpy.ndarray'>
The data type of x is: int64


### Create numpy array

Try out some of these ways of creating NumPy arrays. See if you can produce:

* a NumPy array from a list of numbers,
* a 3-dimensional NumPy array filled with a constant value -- either 0 or 1,
* a NumPy array filled with a constant value -- not 0 or 1. (Hint: this can be achieved using the last array you created, or you could use np.empty and find a way of filling the array with a constant value),
* a NumPy array of 8 elements with a range of values starting from 0 and a spacing of 3 between each element, and
* a NumPy array of 10 elements that are logarithmically spaced.


In [11]:
x = np.array([5,7,9,12,12,23])
x

array([ 5,  7,  9, 12, 12, 23])

In [30]:
array3d_ones=np.ones((2, 3,4))

array3d_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
3*array3d_ones


array([[[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [39]:
np.arange(0,8*3,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [41]:
xlogspace=np.logspace(0,1,num=10)
xlogspace

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [42]:
x=np.random.random((8,))
x

array([0.01636367, 0.27669046, 0.48567538, 0.07670179, 0.31165723,
       0.11422597, 0.15987295, 0.7780655 ])

How could you change the shape of the 8-element array you created previously to have shape (2, 2, 2)? Hint: this can be done without creating a new array.

In [47]:
data=np.reshape(x,(2,2,2))
data

array([[[0.01636367, 0.27669046],
        [0.48567538, 0.07670179]],

       [[0.31165723, 0.11422597],
        [0.15987295, 0.7780655 ]]])

### Indexing

Note that the NumPy arrays are zero-indexed:

In [53]:
data = np.random.randn(10000, 5)
data

array([[-0.48856351,  1.7233873 , -1.74234729,  0.42568931, -0.65376577],
       [-0.17762385, -1.78048461, -0.30958892, -1.07202891,  0.45975868],
       [-0.17106873,  0.40069878, -0.64398134, -0.039872  ,  1.76960064],
       ...,
       [-0.41171367, -0.40128991, -0.70249684, -0.29629702,  0.93316652],
       [ 0.17705455,  1.28445965,  0.54680514, -0.5258101 , -1.17221438],
       [ 0.40423657, -0.04203147,  0.26980611, -1.10251581,  0.91709242]])

In [56]:
data[0, 0]

-0.4885635111154754

It means that that the third element in the first row has an index of [0, 2]:

In [50]:
data[0, 2]

-1.9181830536265574

We can also assign the element with a new value:

In [51]:
data[0, 2] = 100.
print(data[0, 2])

100.0


NumPy (and Python in general) checks the bounds of the array:

In [57]:
print(data.shape)
data[60, 10]

(10000, 5)


IndexError: index 10 is out of bounds for axis 1 with size 5

Finally, we can ask for several elements at once:

In [58]:
data[0, [0, 3]]

array([-0.48856351,  0.42568931])

You can even pass a negative index. It will go from the end of the array.

In [59]:
data[-1, -1]

0.9170924174445896

In [60]:
data[data.shape[0] - 1, data.shape[1] - 1]

0.9170924174445896

### Slices

You can select ranges of elements using slices. To select first two columns from the first row, you can use:

In [61]:
data[0, 0:2]

array([-0.48856351,  1.7233873 ])

Note that the returned array does not include third column (with index 2).

You can skip the first or last index (which means, take the values from the beginning or to the end):

In [62]:
data[0, :2]

array([-0.48856351,  1.7233873 ])

If you omit both indices in the slice leaving out only the colon (:), you will get all columns of this row:

In [63]:
data[0, :]

array([-0.48856351,  1.7233873 , -1.74234729,  0.42568931, -0.65376577])

### Filtering data

In [64]:
data

array([[-0.48856351,  1.7233873 , -1.74234729,  0.42568931, -0.65376577],
       [-0.17762385, -1.78048461, -0.30958892, -1.07202891,  0.45975868],
       [-0.17106873,  0.40069878, -0.64398134, -0.039872  ,  1.76960064],
       ...,
       [-0.41171367, -0.40128991, -0.70249684, -0.29629702,  0.93316652],
       [ 0.17705455,  1.28445965,  0.54680514, -0.5258101 , -1.17221438],
       [ 0.40423657, -0.04203147,  0.26980611, -1.10251581,  0.91709242]])

We can produce a boolean array when using comparison operators.

In [65]:
data > 0

array([[False,  True, False,  True, False],
       [False, False, False, False,  True],
       [False,  True, False, False,  True],
       ...,
       [False, False, False, False,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True, False,  True]])

This mask can be used to select some specific data.

In [66]:
data[data > 0]

array([1.7233873 , 0.42568931, 0.45975868, ..., 0.40423657, 0.26980611,
       0.91709242])

It can also be used to affect some new values

In [67]:
data[data > 0] = np.inf
data

array([[-0.48856351,         inf, -1.74234729,         inf, -0.65376577],
       [-0.17762385, -1.78048461, -0.30958892, -1.07202891,         inf],
       [-0.17106873,         inf, -0.64398134, -0.039872  ,         inf],
       ...,
       [-0.41171367, -0.40128991, -0.70249684, -0.29629702,         inf],
       [        inf,         inf,         inf, -0.5258101 , -1.17221438],
       [        inf, -0.04203147,         inf, -1.10251581,         inf]])

Answer the following quizz:

* Print the element in the $1^{st}$ row and $10^{th}$ cloumn of the data.
* Print the elements in the $3^{rd}$ row and columns of $3^{rd}$ and $15^{th}$.
* Print the elements in the $4^{th}$ row and columns from $3^{rd}$ t0 $15^{th}$.
* Print all the elements in column $15$ which their value is above 0.

In [68]:
data = np.random.randn(20, 20)

In [69]:
data[0,9]

-1.234702309631855

In [74]:
data[2,[2,14]]

array([-0.11586743,  1.49269225])

In [75]:
data[3,2:15]

array([ 0.27962811,  0.32656788,  0.0646692 ,  0.08453093,  0.82409379,
       -0.57652382, -0.51039477,  0.98945852,  0.0975382 , -1.16848308,
       -0.55553278, -0.88450568,  0.47219351])

In [79]:
x=data[:,14]
x[x>0]

array([1.49269225, 0.47219351, 0.736974  , 0.38296306, 1.0513189 ,
       0.16819863, 0.0154667 , 0.44841344, 0.23676586])

### Broadcasting

Broadcasting applies these three rules:

* If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

* If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

* If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data. In the example above the operation is carried out as if the scalar 1.5 was a 1D array with 1.5 in all of its entries, but no actual array is ever created. This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.

<img src="broadcasting.png">

Replicate the above exercises. In addition, how would you make the matrix multiplication between 2 matrices.

In [81]:
X = np.random.random((1, 3))
Y = np.random.random((3, 5))

In [82]:
np.dot(X,Y)

array([[0.30869004, 0.81803506, 0.54124963, 0.58420578, 0.33115067]])

In [83]:
X@Y

array([[0.30869004, 0.81803506, 0.54124963, 0.58420578, 0.33115067]])

### Views on Arrays

NumPy attempts to not make copies of arrays. Many NumPy operations will produce a reference to an existing array, known as a "view", instead of making a whole new array. For example, indexing and reshaping provide a view of the same memory wherever possible.


In [84]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [[1000    1    2    3]
 [   4    5    6    7]]


What this means is that if one array (`arr`) is modified, the other (`arr_view`) will also be updated : the same memory is being shared. This is a valuable tool which enables the system memory overhead to be managed, which is particularly useful when handling lots of large arrays. The lack of copying allows for very efficient vectorized operations.

Remember, this behaviour is automatic in most of NumPy, so it requires some consideration in your code, it can lead to some bugs that are hard to track down. For example, if you are changing some elements of an array that you are using elsewhere, you may want to explicitly copy that array before making changes. If in doubt, you can always copy the data to a different block of memory with the copy() method.

For example:

In [85]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4).copy()

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [[0 1 2 3]
 [4 5 6 7]]


### Final exercise

In [86]:
def trapz_slow(x, y):
    area = 0.
    for i in range(1, len(x)):
        area += (x[i] - x[i-1]) * (y[i] + y[i-1])
    return area / 2

#### Part 1

Create two arrays $x$
and $y$, where $x$ is a linearly spaced array in the interval $[0,3]$ of length 3000, and y represents the function $f(x)=x^2$ sampled at $x$

#### Part 2

Use indexing (not a for loop) to find the 10 values representing $y_i+y_{i−1}$
for i between 1 and 11.

Hint: What indexing would be needed to get all but the last element of the 1d array `y`. Similarly what indexing would be needed to get all but the first element of a 1d array.

#### Part 3

Write a function `trapz(x, y)`, that applies the trapezoid formula to pre-computed values, where x and y are 1-d arrays. The function should not use a for loop.

#### Part 4

Verify that your function is correct by using the arrays created in #1 as input to trapz. Your answer should be a close approximation of $\sum 30 x^2$ which is 9

#### Part 5 (extension)

`numpy` and `scipy.integrate` provide many common integration schemes. Find the documentation for NumPy's own version of the trapezoidal integration scheme and check its result with your own.

In [89]:
x=np.linspace(0,3,3000)


In [93]:
y=x*x


In [97]:
y1=y[0:10]
y2=y[1:11]
y1+y2

array([1.00066700e-06, 5.00333500e-06, 1.30086710e-05, 2.50166750e-05,
       4.10273470e-05, 6.10406870e-05, 8.50566950e-05, 1.13075371e-04,
       1.45096715e-04, 1.81120727e-04])